@startuml
autonumber
actor Client as Client

participant listFiles as listFiles
participant getExcelSheet as getExcelSheet
participant uploadFile as uploadFile
participant generateTemplate as generateTemplate

Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles -> listFiles: listFiles()
activate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles --> listFiles: return
deactivate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> getExcelSheet: getExcelSheet()
activate getExcelSheet
getExcelSheet --> Client: return
deactivate getExcelSheet
Client -> uploadFile: uploadFile()
activate uploadFile
uploadFile --> Client: return
deactivate uploadFile
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> getExcelSheet: getExcelSheet()
activate getExcelSheet
getExcelSheet --> Client: return
deactivate getExcelSheet
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> uploadFile: uploadFile()
activate uploadFile
uploadFile --> Client: return
deactivate uploadFile
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> generateTemplate: generateTemplate()
activate generateTemplate
generateTemplate -> listFiles: listFiles()
activate listFiles
listFiles --> generateTemplate: return
deactivate listFiles
generateTemplate --> Client: return
deactivate generateTemplate
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
Client -> listFiles: listFiles()
activate listFiles
listFiles --> Client: return
deactivate listFiles
@enduml