name: Build and Test Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build docker-compose services
      run: docker compose up -d --build

    - name: Wait for services to initialize
      run: sleep 10

    - name: Install dependencies for automated tests
      working-directory: Pruebas_Automatizadas
      run: npm install

    - name: Install Playwright browsers
      working-directory: Pruebas_Automatizadas
      run: sudo ./node_modules/.bin/playwright install


    - name: Run Chromium test
      working-directory: Pruebas_Automatizadas
      run: node login_correcto.js

    - name: Stop containers
      run: docker compose down
